GeneralizedIndex = int

FINALIZED_ROOT_GINDEX = GeneralizedIndex(105)
CURRENT_SYNC_COMMITTEE_GINDEX = GeneralizedIndex(54)
NEXT_SYNC_COMMITTEE_GINDEX = GeneralizedIndex(55)
EXECUTION_PAYLOAD_GINDEX = GeneralizedIndex(25)
FINALIZED_ROOT_GINDEX_ELECTRA = GeneralizedIndex(169)
CURRENT_SYNC_COMMITTEE_GINDEX_ELECTRA = GeneralizedIndex(86)
NEXT_SYNC_COMMITTEE_GINDEX_ELECTRA = GeneralizedIndex(87)
